# Generated by Django 4.1.6 on 2023-02-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catagory', '0004_alter_catagory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=50, null=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catagory.catagory')),
            ],
        ),
    ]
