# Generated by Django 4.1.6 on 2023-02-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0002_rename_id_catagory_idd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='IDDD',
            new_name='id',
        ),
    ]
