# Generated by Django 4.1.6 on 2023-02-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='id',
            new_name='IDDDD',
        ),
    ]
